// http://gfeljm.tianqiapi.com/api?unescape=1&version=v9&appid=12784242&appsecret=1GwF8Axa&city=%E4%B8%8A%E6%B5%B7
// http://tianqiapi.com/user/order

const test = {
  cityid: '101121501',
  date: '2025-11-15',
  week: '星期六',
  update_time: '17:52',
  city: '日照',
  cityEn: 'rizhao',
  country: '中国',
  countryEn: 'China',
  wea: '霾',
  wea_img: 'wu',
  tem: '15.5',
  tem1: '18',
  tem2: '10',
  win: '南风',
  win_speed: '1级',
  win_meter: '3km/h',
  humidity: '67%',
  visibility: '4km',
  pressure: '1015',
  air: '109',
  air_pm25: '82',
  air_level: '轻度污染',
  air_tips: '易感人群症状有轻度加剧，健康人群出现刺激症状。',
  alarm: [
    {
      alarm_type: '寒潮',
      alarm_level: '蓝色',
      alarm_title: '山东省日照市发布寒潮蓝色预警',
      alarm_content: '日照市气象台2025年11月15日16时30分发布东港区、岚山区寒潮蓝色预警信号：受强冷空气影响，16—18日我市将出现一次寒潮天气，气温明显下降，过程降温幅度10℃左右，最低气温出现在18日早晨，海岸线一带1℃，沿海地区-1℃左右，内陆地区-4℃左右；16日中午至18日白天偏北风风力较大，最大风力内陆5级、阵风7～8级，沿海及近海海域6级、阵风8～9级，海上7～8级、阵风9～10级。\n' +
        '此次寒潮过程对海上生产、能源保供、交通运输、室外作业、农业生产、森林防灭火和人体健康等有不利影响，请提前做好防范工作。（预警信息来源：国家预警信息发布中心）'
    },
    {
      alarm_type: '寒潮',
      alarm_level: '蓝色',
      alarm_title: '山东省日照市发布寒潮蓝色预警',
      alarm_content: '日照市气象台2025年11月15日16时30分发布东港区、岚山区寒潮蓝色预警信号：受强冷空气影响，16—18日我市将出现一次寒潮天气，气温明显下降，过程降温幅度10℃左右，最低气温出现在18日早晨，海岸线一带1℃，沿海地区-1℃左右，内陆地区-4℃左右；16日中午至18日白天偏北风风力较大，最大风力内陆5级、阵风7～8级，沿海及近海海域6级、阵风8～9级，海上7～8级、阵风9～10级。\n' +
        '此次寒潮过程对海上生产、能源保供、交通运输、室外作业、农业生产、森林防灭火和人体健康等有不利影响，请提前做好防范工作。（预警信息来源：国家预警信息发布中心）'
    },
    {
      alarm_type: '大风',
      alarm_level: '黄色',
      alarm_title: '山东省日照市发布大风黄色预警',
      alarm_content: '日照市气象台2025年11月15日16时30分发布东港区、岚山区大风黄色预警信号：受强冷空气影响，预计16日中午至18日白天偏北风风力较大，最大风力内陆5级、阵风7～8级，沿海及近海海域6级、阵风8～9级，海上7～8级、阵风9～10级。18日夜间风力逐渐减弱。（预警信息来源：国家预警信息发布中心）'
    },
    {
      alarm_type: '大风',
      alarm_level: '黄色',
      alarm_title: '山东省日照市发布大风黄色预警',
      alarm_content: '日照市气象台2025年11月15日16时30分发布东港区、岚山区大风黄色预警信号：受强冷空气影响，预计16日中午至18日白天偏北风风力较大，最大风力内陆5级、阵风7～8级，沿海及近海海域6级、阵风8～9级，海上7～8级、阵风9～10级。18日夜间风力逐渐减弱。（预警信息来源：国家预警信息发布中心）'
    }
  ],
  rain_pcpn: '0',
  uvIndex: '1',
  uvDescription: '低',
  wea_day: '多云',
  wea_day_img: 'yun',
  wea_night: '多云',
  wea_night_img: 'yun',
  sunrise: '06:37',
  sunset: '16:55',
  hours: [
    {
      hours: '17:00',
      wea: '轻度雾霾',
      wea_img: 'wu',
      tem: '14',
      win: '西南风',
      win_speed: '2级',
      vis: '20.63',
      aqinum: '110',
      aqi: '轻度污染'
    },
    {
      hours: '18:00',
      wea: '轻度雾霾',
      wea_img: 'wu',
      tem: '13',
      win: '南风',
      win_speed: '2级',
      vis: '18.25',
      aqinum: '117',
      aqi: '轻度污染'
    },
    {
      hours: '19:00',
      wea: '轻度雾霾',
      wea_img: 'wu',
      tem: '12',
      win: '西南风',
      win_speed: '2级',
      vis: '18.16',
      aqinum: '122',
      aqi: '轻度污染'
    },
    {
      hours: '20:00',
      wea: '轻度雾霾',
      wea_img: 'wu',
      tem: '11',
      win: '西南风',
      win_speed: '1级',
      vis: '18.74',
      aqinum: '127',
      aqi: '轻度污染'
    },
    {
      hours: '21:00',
      wea: '轻度雾霾',
      wea_img: 'wu',
      tem: '11',
      win: '西南风',
      win_speed: '2级',
      vis: '18.28',
      aqinum: '129',
      aqi: '轻度污染'
    },
    {
      hours: '22:00',
      wea: '轻度雾霾',
      wea_img: 'wu',
      tem: '11',
      win: '西南风',
      win_speed: '2级',
      vis: '17.25',
      aqinum: '129',
      aqi: '轻度污染'
    },
    {
      hours: '23:00',
      wea: '雾',
      wea_img: 'wu',
      tem: '11',
      win: '西南风',
      win_speed: '2级',
      vis: '16.2',
      aqinum: '128',
      aqi: '轻度污染'
    },
    {
      hours: '00:00',
      wea: '轻度雾霾',
      wea_img: 'wu',
      tem: '10',
      win: '西南风',
      win_speed: '2级',
      vis: '15.66',
      aqinum: '127',
      aqi: '轻度污染'
    },
    {
      hours: '01:00',
      wea: '轻度雾霾',
      wea_img: 'wu',
      tem: '10',
      win: '西南风',
      win_speed: '2级',
      vis: '15.93',
      aqinum: '127',
      aqi: '轻度污染'
    },
    {
      hours: '02:00',
      wea: '轻度雾霾',
      wea_img: 'wu',
      tem: '10',
      win: '西南风',
      win_speed: '2级',
      vis: '16.54',
      aqinum: '127',
      aqi: '轻度污染'
    },
    {
      hours: '03:00',
      wea: '轻度雾霾',
      wea_img: 'wu',
      tem: '10',
      win: '西南风',
      win_speed: '2级',
      vis: '16.82',
      aqinum: '127',
      aqi: '轻度污染'
    },
    {
      hours: '04:00',
      wea: '轻度雾霾',
      wea_img: 'wu',
      tem: '9',
      win: '西南风',
      win_speed: '2级',
      vis: '17.28',
      aqinum: '129',
      aqi: '轻度污染'
    },
    {
      hours: '05:00',
      wea: '轻度雾霾',
      wea_img: 'wu',
      tem: '9',
      win: '西南风',
      win_speed: '1级',
      vis: '17.65',
      aqinum: '130',
      aqi: '轻度污染'
    },
    {
      hours: '06:00',
      wea: '轻度雾霾',
      wea_img: 'wu',
      tem: '9',
      win: '西南风',
      win_speed: '1级',
      vis: '17.54',
      aqinum: '134',
      aqi: '轻度污染'
    },
    {
      hours: '07:00',
      wea: '轻度雾霾',
      wea_img: 'wu',
      tem: '9',
      win: '西南风',
      win_speed: '1级',
      vis: '16.78',
      aqinum: '137',
      aqi: '轻度污染'
    },
    {
      hours: '08:00',
      wea: '轻度雾霾',
      wea_img: 'wu',
      tem: '11',
      win: '西北风',
      win_speed: '1级',
      vis: '17.97',
      aqinum: '139',
      aqi: '轻度污染'
    },
    {
      hours: '09:00',
      wea: '轻度雾霾',
      wea_img: 'wu',
      tem: '12',
      win: '西北风',
      win_speed: '2级',
      vis: '21.25',
      aqinum: '143',
      aqi: '轻度污染'
    },
    {
      hours: '10:00',
      wea: '轻度雾霾',
      wea_img: 'wu',
      tem: '14',
      win: '西风',
      win_speed: '2级',
      vis: '23.09',
      aqinum: '145',
      aqi: '轻度污染'
    },
    {
      hours: '11:00',
      wea: '轻度雾霾',
      wea_img: 'wu',
      tem: '16',
      win: '西北风',
      win_speed: '3级',
      vis: '24.93',
      aqinum: '142',
      aqi: '轻度污染'
    },
    {
      hours: '12:00',
      wea: '轻度雾霾',
      wea_img: 'wu',
      tem: '16',
      win: '西北风',
      win_speed: '4级',
      vis: '23.62',
      aqinum: '137',
      aqi: '轻度污染'
    },
    {
      hours: '13:00',
      wea: '轻度雾霾',
      wea_img: 'wu',
      tem: '16',
      win: '北风',
      win_speed: '4级',
      vis: '25.88',
      aqinum: '130',
      aqi: '轻度污染'
    },
    {
      hours: '14:00',
      wea: '轻度雾霾',
      wea_img: 'wu',
      tem: '15',
      win: '北风',
      win_speed: '4级',
      vis: '25.01',
      aqinum: '119',
      aqi: '轻度污染'
    },
    {
      hours: '15:00',
      wea: '轻度雾霾',
      wea_img: 'wu',
      tem: '13',
      win: '北风',
      win_speed: '5级',
      vis: '31.13',
      aqinum: '111',
      aqi: '轻度污染'
    },
    {
      hours: '16:00',
      wea: '大风',
      wea_img: 'qing',
      tem: '12',
      win: '北风',
      win_speed: '5级',
      vis: '36.15',
      aqinum: '109',
      aqi: '轻度污染'
    },
    {
      hours: '17:00',
      wea: '大风',
      wea_img: 'qing',
      tem: '10',
      win: '北风',
      win_speed: '5级',
      vis: '39.5',
      aqinum: '104',
      aqi: '轻度污染'
    },
    {
      hours: '18:00',
      wea: '晴',
      wea_img: 'qing',
      tem: '9',
      win: '北风',
      win_speed: '5级',
      vis: '40.11',
      aqinum: '97',
      aqi: '良'
    }
  ],
  aqi: {
    update_time: '17:48',
    cityid: '101121501',
    city: '日照市',
    cityEn: '',
    country: '',
    countryEn: '',
    air: '109',
    air_level: '轻度污染',
    air_tips: '易感人群症状有轻度加剧，健康人群出现刺激症状。',
    pp: '细颗粒物(PM2.5)',
    pm25: '82',
    pm25_desc: '轻度污染',
    pm10: '153',
    pm10_desc: '中度污染',
    o3: '126',
    o3_desc: '',
    no2: '59',
    no2_desc: '',
    so2: '15',
    so2_desc: '',
    co: '1',
    co_desc: '',
    kouzhao: '不用佩戴口罩',
    yundong: '适宜运动',
    waichu: '不适宜外出',
    kaichuang: '适宜开窗',
    jinghuaqi: '不需要打开'
  },
  nums: 2,
  cityName: '日照'
}
